# Generated by Django 4.2.5 on 2023-09-27 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="intruder_image/%Y/%m/%d/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 27, 7, 12, 52, 323277, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
