# Generated by Django 4.2.5 on 2023-09-27 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image_alter_post_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 27, 14, 1, 30, 760381, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
