# Generated by Django 4.2.5 on 2023-09-27 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 27, 14, 10, 10, 861443, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
